gen:
    author: ruoyi
    autoRemovePre: false
    packageName: com.ruoyi.project.system
    tablePrefix: sys_
logging:
    level:
        com:
            ruoyi: debug
        org:
            springframework: warn
mybatis:
    configLocation: classpath:mybatis/mybatis-config.xml
    mapperLocations: classpath*:mybatis/**/*Mapper.xml
    typeAliasesPackage: com.ruoyi.project.**.domain
pagehelper:
    helperDialect: mysql
    params: count=countSql
    reasonable: true
    supportMethodsArguments: true
ruoyi:
    addressEnabled: true
    copyrightYear: 2019
    demoEnabled: true
    name: RuoYi
    profile: D:/ruoyi/uploadPath
    version: 2.0.0
server:
    port: 8080
    servlet:
        context-path: /
    tomcat:
        max-threads: 800
        min-spare-threads: 30
        uri-encoding: UTF-8
spring:
    devtools:
        restart:
            enabled: true
    messages:
        basename: i18n/messages
    mvc:
        static-path-pattern: /**
    profiles:
        active: druid
    redis:
        host: localhost
        lettuce:
            pool:
                max-active: 8
                max-idle: 8
                max-wait: -1ms
                min-idle: 0
        port: 6379
        timeout: 10s
    resources:
        static-locations: classpath:/
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 20MB
token:
    expireTime: 30
    header: Authorization
    secret: abcdefghijklmnopqrstuvwxyz
xss:
    enabled: true
    excludes: /system/notice/*
    urlPatterns: /system/*,/monitor/*,/tool/*